// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/subscription (interfaces: PipelineStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_pipeline_store.go -package=mocks github.com/kdwils/baldsky/subscription PipelineStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPipelineStore is a mock of PipelineStore interface.
type MockPipelineStore struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineStoreMockRecorder
	isgomock struct{}
}

// MockPipelineStoreMockRecorder is the mock recorder for MockPipelineStore.
type MockPipelineStoreMockRecorder struct {
	mock *MockPipelineStore
}

// NewMockPipelineStore creates a new mock instance.
func NewMockPipelineStore(ctrl *gomock.Controller) *MockPipelineStore {
	mock := &MockPipelineStore{ctrl: ctrl}
	mock.recorder = &MockPipelineStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineStore) EXPECT() *MockPipelineStoreMockRecorder {
	return m.recorder
}

// DeletePosts mocks base method.
func (m *MockPipelineStore) DeletePosts(ctx context.Context, uris []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePosts", ctx, uris)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePosts indicates an expected call of DeletePosts.
func (mr *MockPipelineStoreMockRecorder) DeletePosts(ctx, uris any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePosts", reflect.TypeOf((*MockPipelineStore)(nil).DeletePosts), ctx, uris)
}

// InsertPost mocks base method.
func (m *MockPipelineStore) InsertPost(ctx context.Context, feedName, uri, cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPost", ctx, feedName, uri, cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPost indicates an expected call of InsertPost.
func (mr *MockPipelineStoreMockRecorder) InsertPost(ctx, feedName, uri, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPost", reflect.TypeOf((*MockPipelineStore)(nil).InsertPost), ctx, feedName, uri, cid)
}
