// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/subscription (interfaces: CursorStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cursor_store.go -package=mocks github.com/kdwils/baldsky/subscription CursorStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCursorStore is a mock of CursorStore interface.
type MockCursorStore struct {
	ctrl     *gomock.Controller
	recorder *MockCursorStoreMockRecorder
	isgomock struct{}
}

// MockCursorStoreMockRecorder is the mock recorder for MockCursorStore.
type MockCursorStoreMockRecorder struct {
	mock *MockCursorStore
}

// NewMockCursorStore creates a new mock instance.
func NewMockCursorStore(ctrl *gomock.Controller) *MockCursorStore {
	mock := &MockCursorStore{ctrl: ctrl}
	mock.recorder = &MockCursorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursorStore) EXPECT() *MockCursorStoreMockRecorder {
	return m.recorder
}

// GetCursor mocks base method.
func (m *MockCursorStore) GetCursor(ctx context.Context, service string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursor", ctx, service)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCursor indicates an expected call of GetCursor.
func (mr *MockCursorStoreMockRecorder) GetCursor(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursor", reflect.TypeOf((*MockCursorStore)(nil).GetCursor), ctx, service)
}

// UpsertCursor mocks base method.
func (m *MockCursorStore) UpsertCursor(ctx context.Context, service string, cursor int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCursor", ctx, service, cursor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCursor indicates an expected call of UpsertCursor.
func (mr *MockCursorStoreMockRecorder) UpsertCursor(ctx, service, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCursor", reflect.TypeOf((*MockCursorStore)(nil).UpsertCursor), ctx, service, cursor)
}
