// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/feed (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_feed_store.go -package=mocks github.com/kdwils/baldsky/feed Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	feed "github.com/kdwils/baldsky/feed"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeletePost mocks base method.
func (m *MockStore) DeletePost(ctx context.Context, uri string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, uri)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockStoreMockRecorder) DeletePost(ctx, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockStore)(nil).DeletePost), ctx, uri)
}

// DeletePosts mocks base method.
func (m *MockStore) DeletePosts(ctx context.Context, uris []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePosts", ctx, uris)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePosts indicates an expected call of DeletePosts.
func (mr *MockStoreMockRecorder) DeletePosts(ctx, uris any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePosts", reflect.TypeOf((*MockStore)(nil).DeletePosts), ctx, uris)
}

// GetCursor mocks base method.
func (m *MockStore) GetCursor(ctx context.Context, service string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursor", ctx, service)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCursor indicates an expected call of GetCursor.
func (mr *MockStoreMockRecorder) GetCursor(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursor", reflect.TypeOf((*MockStore)(nil).GetCursor), ctx, service)
}

// GetFeedPage mocks base method.
func (m *MockStore) GetFeedPage(ctx context.Context, feedName string, limit int, cursor *string) (feed.FeedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedPage", ctx, feedName, limit, cursor)
	ret0, _ := ret[0].(feed.FeedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedPage indicates an expected call of GetFeedPage.
func (mr *MockStoreMockRecorder) GetFeedPage(ctx, feedName, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedPage", reflect.TypeOf((*MockStore)(nil).GetFeedPage), ctx, feedName, limit, cursor)
}

// InsertPost mocks base method.
func (m *MockStore) InsertPost(ctx context.Context, feedName, uri, cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPost", ctx, feedName, uri, cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPost indicates an expected call of InsertPost.
func (mr *MockStoreMockRecorder) InsertPost(ctx, feedName, uri, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPost", reflect.TypeOf((*MockStore)(nil).InsertPost), ctx, feedName, uri, cid)
}

// PostExists mocks base method.
func (m *MockStore) PostExists(ctx context.Context, feedName, uri string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostExists", ctx, feedName, uri)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostExists indicates an expected call of PostExists.
func (mr *MockStoreMockRecorder) PostExists(ctx, feedName, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostExists", reflect.TypeOf((*MockStore)(nil).PostExists), ctx, feedName, uri)
}

// UpsertCursor mocks base method.
func (m *MockStore) UpsertCursor(ctx context.Context, service string, cursor int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCursor", ctx, service, cursor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCursor indicates an expected call of UpsertCursor.
func (mr *MockStoreMockRecorder) UpsertCursor(ctx, service, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCursor", reflect.TypeOf((*MockStore)(nil).UpsertCursor), ctx, service, cursor)
}
