// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/db/gen (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=feed/mocks/mock_querier.go -package=mocks github.com/kdwils/baldsky/db/gen Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gen "github.com/kdwils/baldsky/db/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// DeletePost mocks base method.
func (m *MockQuerier) DeletePost(ctx context.Context, uri string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, uri)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockQuerierMockRecorder) DeletePost(ctx, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockQuerier)(nil).DeletePost), ctx, uri)
}

// GetCursor mocks base method.
func (m *MockQuerier) GetCursor(ctx context.Context, service string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursor", ctx, service)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCursor indicates an expected call of GetCursor.
func (mr *MockQuerierMockRecorder) GetCursor(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursor", reflect.TypeOf((*MockQuerier)(nil).GetCursor), ctx, service)
}

// GetFeedPage mocks base method.
func (m *MockQuerier) GetFeedPage(ctx context.Context, arg gen.GetFeedPageParams) ([]gen.GetFeedPageRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedPage", ctx, arg)
	ret0, _ := ret[0].([]gen.GetFeedPageRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedPage indicates an expected call of GetFeedPage.
func (mr *MockQuerierMockRecorder) GetFeedPage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedPage", reflect.TypeOf((*MockQuerier)(nil).GetFeedPage), ctx, arg)
}

// GetPostExists mocks base method.
func (m *MockQuerier) GetPostExists(ctx context.Context, arg gen.GetPostExistsParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostExists", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostExists indicates an expected call of GetPostExists.
func (mr *MockQuerierMockRecorder) GetPostExists(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostExists", reflect.TypeOf((*MockQuerier)(nil).GetPostExists), ctx, arg)
}

// InsertPost mocks base method.
func (m *MockQuerier) InsertPost(ctx context.Context, arg gen.InsertPostParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPost", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPost indicates an expected call of InsertPost.
func (mr *MockQuerierMockRecorder) InsertPost(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPost", reflect.TypeOf((*MockQuerier)(nil).InsertPost), ctx, arg)
}

// UpsertCursor mocks base method.
func (m *MockQuerier) UpsertCursor(ctx context.Context, arg gen.UpsertCursorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCursor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCursor indicates an expected call of UpsertCursor.
func (mr *MockQuerierMockRecorder) UpsertCursor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCursor", reflect.TypeOf((*MockQuerier)(nil).UpsertCursor), ctx, arg)
}
