// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/server (interfaces: WorkerChecker)
//
// Generated by this command:
//
//	mockgen -destination=mock_worker_checker.go -package=mocks github.com/kdwils/baldsky/server WorkerChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkerChecker is a mock of WorkerChecker interface.
type MockWorkerChecker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerCheckerMockRecorder
	isgomock struct{}
}

// MockWorkerCheckerMockRecorder is the mock recorder for MockWorkerChecker.
type MockWorkerCheckerMockRecorder struct {
	mock *MockWorkerChecker
}

// NewMockWorkerChecker creates a new mock instance.
func NewMockWorkerChecker(ctrl *gomock.Controller) *MockWorkerChecker {
	mock := &MockWorkerChecker{ctrl: ctrl}
	mock.recorder = &MockWorkerCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerChecker) EXPECT() *MockWorkerCheckerMockRecorder {
	return m.recorder
}

// Connected mocks base method.
func (m *MockWorkerChecker) Connected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Connected indicates an expected call of Connected.
func (mr *MockWorkerCheckerMockRecorder) Connected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connected", reflect.TypeOf((*MockWorkerChecker)(nil).Connected))
}
