// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/server (interfaces: FirehoseChecker)
//
// Generated by this command:
//
//	mockgen -destination=server/mocks/mock_firehose_checker.go -package=mocks github.com/kdwils/baldsky/server FirehoseChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFirehoseChecker is a mock of FirehoseChecker interface.
type MockFirehoseChecker struct {
	ctrl     *gomock.Controller
	recorder *MockFirehoseCheckerMockRecorder
	isgomock struct{}
}

// MockFirehoseCheckerMockRecorder is the mock recorder for MockFirehoseChecker.
type MockFirehoseCheckerMockRecorder struct {
	mock *MockFirehoseChecker
}

// NewMockFirehoseChecker creates a new mock instance.
func NewMockFirehoseChecker(ctrl *gomock.Controller) *MockFirehoseChecker {
	mock := &MockFirehoseChecker{ctrl: ctrl}
	mock.recorder = &MockFirehoseCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirehoseChecker) EXPECT() *MockFirehoseCheckerMockRecorder {
	return m.recorder
}

// Connected mocks base method.
func (m *MockFirehoseChecker) Connected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Connected indicates an expected call of Connected.
func (mr *MockFirehoseCheckerMockRecorder) Connected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connected", reflect.TypeOf((*MockFirehoseChecker)(nil).Connected))
}
