// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/baldsky/server (interfaces: FeedService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_feed_service.go -package=mocks github.com/kdwils/baldsky/server FeedService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	feed "github.com/kdwils/baldsky/feed"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
	isgomock struct{}
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// GetDIDDocument mocks base method.
func (m *MockFeedService) GetDIDDocument() feed.DIDDocument {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDIDDocument")
	ret0, _ := ret[0].(feed.DIDDocument)
	return ret0
}

// GetDIDDocument indicates an expected call of GetDIDDocument.
func (mr *MockFeedServiceMockRecorder) GetDIDDocument() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDIDDocument", reflect.TypeOf((*MockFeedService)(nil).GetDIDDocument))
}

// GetFeedDescription mocks base method.
func (m *MockFeedService) GetFeedDescription() feed.FeedDescription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedDescription")
	ret0, _ := ret[0].(feed.FeedDescription)
	return ret0
}

// GetFeedDescription indicates an expected call of GetFeedDescription.
func (mr *MockFeedServiceMockRecorder) GetFeedDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedDescription", reflect.TypeOf((*MockFeedService)(nil).GetFeedDescription))
}

// GetFeedPage mocks base method.
func (m *MockFeedService) GetFeedPage(ctx context.Context, feedURI, limit, cursor string) (feed.FeedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedPage", ctx, feedURI, limit, cursor)
	ret0, _ := ret[0].(feed.FeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedPage indicates an expected call of GetFeedPage.
func (mr *MockFeedServiceMockRecorder) GetFeedPage(ctx, feedURI, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedPage", reflect.TypeOf((*MockFeedService)(nil).GetFeedPage), ctx, feedURI, limit, cursor)
}

// Hostname mocks base method.
func (m *MockFeedService) Hostname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hostname")
	ret0, _ := ret[0].(string)
	return ret0
}

// Hostname indicates an expected call of Hostname.
func (mr *MockFeedServiceMockRecorder) Hostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hostname", reflect.TypeOf((*MockFeedService)(nil).Hostname))
}
